language: php
sudo: false
php:
    - 7.0
    - 7.1
    - 7.2
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - travis_retry composer self-update
install:
  - travis_retry composer update --no-interaction --prefer-source
script:
  - composer test